Utilisateurs:
    type: entity
    table: utilisateurs
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        nom:
            type: text
            nullable: false
            length: null
            options:
                fixed: false
        prenom:
            type: text
            nullable: false
            length: null
            options:
                fixed: false
        adresse:
            type: text
            nullable: true
            length: null
            options:
                fixed: false
        codepostal:
            type: string
            nullable: true
            length: 5
            options:
                fixed: true
        ville:
            type: text
            nullable: true
            length: null
            options:
                fixed: false
        email:
            type: text
            nullable: true
            length: null
            options:
                fixed: false
        sexe:
            type: string
            nullable: true
            length: 1
            options:
                fixed: true
        login:
            type: text
            nullable: true
            length: null
            options:
                fixed: false
        password:
            type: text
            nullable: true
            length: null
            options:
                fixed: false
        telephone:
            type: string
            nullable: true
            length: 20
            options:
                fixed: true
    lifecycleCallbacks: {  }
